### ISSUE TITLE
Incompatible with remark-gfm >2.0.0

### ISSUE THREAD

**Issue by queengooborg** [remcohaszing/remark-prettier#1]
Hi there!

First off, I want to say: thank you for this amazing plugin, it's been a critical step in the Markdown conversion of all of MDN's articles!

I wanted to mention that it appears this package is incompatible with `remark-gfm` past version 2.0.0.  When upgrading, I get the following error:

```
TypeError: Cannot read properties of undefined (reading 'push')
    at containerFlow (file:///Users/queengooborg/Developer/Gooborg/mdn-markdown/node_modules/mdast-util-gfm-task-list-item/node_modules/mdast-util-to-markdown/lib/util/container-flow.js:25:14)
    at listItem (file:///Users/queengooborg/Developer/Gooborg/mdn-markdown/node_modules/mdast-util-gfm-task-list-item/node_modules/mdast-util-to-markdown/lib/handle/list-item.js:50:5)
    at Object.listItemWithTaskListItem (file:///Users/queengooborg/Developer/Gooborg/mdn-markdown/node_modules/mdast-util-gfm-task-list-item/index.js:98:15)
    at Object.one [as handle] (/Users/queengooborg/Developer/Gooborg/mdn-markdown/node_modules/zwitch/index.js:20:25)
    at flow (/Users/queengooborg/Developer/Gooborg/mdn-markdown/node_modules/mdast-util-to-markdown/lib/util/container-flow.js:15:15)
    at Object.list (/Users/queengooborg/Developer/Gooborg/mdn-markdown/node_modules/mdast-util-to-markdown/lib/handle/list.js:7:15)
    at Object.one [as handle] (/Users/queengooborg/Developer/Gooborg/mdn-markdown/node_modules/zwitch/index.js:20:25)
    at flow (/Users/queengooborg/Developer/Gooborg/mdn-markdown/node_modules/mdast-util-to-markdown/lib/util/container-flow.js:15:15)
    at Object.root (/Users/queengooborg/Developer/Gooborg/mdn-markdown/node_modules/mdast-util-to-markdown/lib/handle/root.js:6:10)
    at Object.one [as handle] (/Users/queengooborg/Developer/Gooborg/mdn-markdown/node_modules/zwitch/index.js:20:25)
```

**Comment by remcohaszing** [comment]
**Thank _you_** for working on MDN’s articles! It’s one of the most valuable resources for JavaScript / web developers such as myself.

I have just updated this package to use the latest versions of all dependencies. This should include compatibility with the latest version of `remark-gfm`. Please let me know if you run into any issues. :)

This update does require the use of ESM instead of CJS, but I think you’re already using that.

**Comment by queengooborg** [comment]
Thank you for the quick fix!  I've just updated the packages and confirmed everything is working now!

> **Thank _you_** for working on MDN’s articles! It’s one of the most valuable resources for JavaScript / web developers such as myself.

💜
